version: "3"
services:
  arvapyapi:
    image: arvapy
    environment:
      FLASK_ENV: development
    volumes:
      - ./data/datasets:/datasets # video source files
      - ..:/src/arvapy            # API code
    ports:
      - 5000:5000  # API exposed in port 5000
    tmpfs:
      - /tmp
    
